/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : BookingId,
  'customerName' : string,
  'status' : BookingStatus,
  'date' : DateStr,
  'createdAt' : Timestamp,
  'serviceId' : ServiceId,
  'customerEmail' : string,
  'timeSlot' : TimeStr,
}
export type BookingId = bigint;
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface CreateBookingRequest {
  'customerName' : string,
  'date' : DateStr,
  'serviceId' : ServiceId,
  'customerEmail' : string,
  'timeSlot' : TimeStr,
}
export interface CreateServiceRequest {
  'name' : string,
  'description' : string,
  'durationMinutes' : bigint,
  'price' : string,
}
export type DateStr = string;
export interface DayAvailability {
  'day' : DayOfWeek,
  'ranges' : Array<TimeRange>,
}
export type DayOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export interface Service {
  'id' : ServiceId,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'durationMinutes' : bigint,
  'price' : string,
}
export type ServiceId = bigint;
export interface TimeRange { 'startTime' : TimeStr, 'endTime' : TimeStr }
export interface TimeSlot { 'startTime' : TimeStr, 'isAvailable' : boolean }
export type TimeStr = string;
export type Timestamp = bigint;
export interface UpdateServiceRequest {
  'id' : ServiceId,
  'name' : string,
  'description' : string,
  'durationMinutes' : bigint,
  'price' : string,
}
export type WeeklyAvailability = Array<DayAvailability>;
export interface _SERVICE {
  'cancelBooking' : ActorMethod<[BookingId], boolean>,
  'createBooking' : ActorMethod<[CreateBookingRequest], BookingId>,
  'createService' : ActorMethod<[CreateServiceRequest], Service>,
  'deleteService' : ActorMethod<[ServiceId], boolean>,
  'getAdmin' : ActorMethod<[], [] | [Principal]>,
  'getAvailability' : ActorMethod<[], WeeklyAvailability>,
  'getAvailableSlots' : ActorMethod<[ServiceId, DateStr], Array<TimeSlot>>,
  'getBooking' : ActorMethod<[BookingId], [] | [Booking]>,
  'getService' : ActorMethod<[ServiceId], [] | [Service]>,
  'listBookings' : ActorMethod<[], Array<Booking>>,
  'listPastBookings' : ActorMethod<[], Array<Booking>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'listUpcomingBookings' : ActorMethod<[], Array<Booking>>,
  'setAdmin' : ActorMethod<[], undefined>,
  'setAvailability' : ActorMethod<[WeeklyAvailability], undefined>,
  'updateBookingStatus' : ActorMethod<[BookingId, BookingStatus], boolean>,
  'updateService' : ActorMethod<[UpdateServiceRequest], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];