/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingId = IDL.Nat;
export const DateStr = IDL.Text;
export const ServiceId = IDL.Nat;
export const TimeStr = IDL.Text;
export const CreateBookingRequest = IDL.Record({
  'customerName' : IDL.Text,
  'date' : DateStr,
  'serviceId' : ServiceId,
  'customerEmail' : IDL.Text,
  'timeSlot' : TimeStr,
});
export const CreateServiceRequest = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'price' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : ServiceId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'durationMinutes' : IDL.Nat,
  'price' : IDL.Text,
});
export const DayOfWeek = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const TimeRange = IDL.Record({
  'startTime' : TimeStr,
  'endTime' : TimeStr,
});
export const DayAvailability = IDL.Record({
  'day' : DayOfWeek,
  'ranges' : IDL.Vec(TimeRange),
});
export const WeeklyAvailability = IDL.Vec(DayAvailability);
export const TimeSlot = IDL.Record({
  'startTime' : TimeStr,
  'isAvailable' : IDL.Bool,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Booking = IDL.Record({
  'id' : BookingId,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'date' : DateStr,
  'createdAt' : Timestamp,
  'serviceId' : ServiceId,
  'customerEmail' : IDL.Text,
  'timeSlot' : TimeStr,
});
export const UpdateServiceRequest = IDL.Record({
  'id' : ServiceId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'price' : IDL.Text,
});

export const idlService = IDL.Service({
  'cancelBooking' : IDL.Func([BookingId], [IDL.Bool], []),
  'createBooking' : IDL.Func([CreateBookingRequest], [BookingId], []),
  'createService' : IDL.Func([CreateServiceRequest], [Service], []),
  'deleteService' : IDL.Func([ServiceId], [IDL.Bool], []),
  'getAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAvailability' : IDL.Func([], [WeeklyAvailability], ['query']),
  'getAvailableSlots' : IDL.Func(
      [ServiceId, DateStr],
      [IDL.Vec(TimeSlot)],
      ['query'],
    ),
  'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
  'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
  'listBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
  'listPastBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'listUpcomingBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
  'setAdmin' : IDL.Func([], [], []),
  'setAvailability' : IDL.Func([WeeklyAvailability], [], []),
  'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [IDL.Bool], []),
  'updateService' : IDL.Func([UpdateServiceRequest], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingId = IDL.Nat;
  const DateStr = IDL.Text;
  const ServiceId = IDL.Nat;
  const TimeStr = IDL.Text;
  const CreateBookingRequest = IDL.Record({
    'customerName' : IDL.Text,
    'date' : DateStr,
    'serviceId' : ServiceId,
    'customerEmail' : IDL.Text,
    'timeSlot' : TimeStr,
  });
  const CreateServiceRequest = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'price' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : ServiceId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'durationMinutes' : IDL.Nat,
    'price' : IDL.Text,
  });
  const DayOfWeek = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const TimeRange = IDL.Record({ 'startTime' : TimeStr, 'endTime' : TimeStr });
  const DayAvailability = IDL.Record({
    'day' : DayOfWeek,
    'ranges' : IDL.Vec(TimeRange),
  });
  const WeeklyAvailability = IDL.Vec(DayAvailability);
  const TimeSlot = IDL.Record({
    'startTime' : TimeStr,
    'isAvailable' : IDL.Bool,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Booking = IDL.Record({
    'id' : BookingId,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'date' : DateStr,
    'createdAt' : Timestamp,
    'serviceId' : ServiceId,
    'customerEmail' : IDL.Text,
    'timeSlot' : TimeStr,
  });
  const UpdateServiceRequest = IDL.Record({
    'id' : ServiceId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'price' : IDL.Text,
  });
  
  return IDL.Service({
    'cancelBooking' : IDL.Func([BookingId], [IDL.Bool], []),
    'createBooking' : IDL.Func([CreateBookingRequest], [BookingId], []),
    'createService' : IDL.Func([CreateServiceRequest], [Service], []),
    'deleteService' : IDL.Func([ServiceId], [IDL.Bool], []),
    'getAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getAvailability' : IDL.Func([], [WeeklyAvailability], ['query']),
    'getAvailableSlots' : IDL.Func(
        [ServiceId, DateStr],
        [IDL.Vec(TimeSlot)],
        ['query'],
      ),
    'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
    'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
    'listBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
    'listPastBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'listUpcomingBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
    'setAdmin' : IDL.Func([], [], []),
    'setAvailability' : IDL.Func([WeeklyAvailability], [], []),
    'updateBookingStatus' : IDL.Func(
        [BookingId, BookingStatus],
        [IDL.Bool],
        [],
      ),
    'updateService' : IDL.Func([UpdateServiceRequest], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };